---
title: "Getting-and-Cleaning-Data-Week-4-Assignment Readme"
author: "Stephen Beaver"
date: "March 6, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Cleaning-Data: Peer Graded Assignment README

Repository Contains:
1. run_analysis.R
2. TidyDataSet.txt
3. codebook_tidy_data_set.rmd
4. README_tidydataset.rmd

## Assignemnt Discription

The purpose of this project is to demonstrate your ability to collect, work with, and clean a data set.

Review criteria
The submitted data set is tidy.
The Github repo contains the required scripts.
GitHub contains a code book that modifies and updates the available codebooks with the data to indicate all the variables and summaries calculated, along with units, and any other relevant information.
The README that explains the analysis files is clear and understandable.
The work submitted for this project is the work of the student who submitted it.
Getting and Cleaning Data Course Projectless 
The purpose of this project is to demonstrate your ability to collect, work with, and clean a data set. The goal is to prepare tidy data that can be used for later analysis. You will be graded by your peers on a series of yes/no questions related to the project. You will be required to submit: 1) a tidy data set as described below, 2) a link to a Github repository with your script for performing the analysis, and 3) a code book that describes the variables, the data, and any transformations or work that you performed to clean up the data called CodeBook.md. You should also include a README.md in the repo with your scripts. This repo explains how all of the scripts work and how they are connected.

One of the most exciting areas in all of data science right now is wearable computing - see for example this article . Companies like Fitbit, Nike, and Jawbone Up are racing to develop the most advanced algorithms to attract new users. The data linked to from the course website represent data collected from the accelerometers from the Samsung Galaxy S smartphone. A full description is available at the site where the data was obtained:

http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones

Here are the data for the project:

https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip

You should create one R script called run_analysis.R that does the following.

Merges the training and the test sets to create one data set.
Extracts only the measurements on the mean and standard deviation for each measurement.
Uses descriptive activity names to name the activities in the data set
Appropriately labels the data set with descriptive variable names.
From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.
Good luck!

## File Descriptions

### run_analysis.R

This file contains the code used to parse and merge the data set for the assignment which was provided in the link:

https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip

### TidyDataSet.txt

This file contains a shorten version of the final merged data with the averages for each variable, grouped by activity and subject.  The file is tab delimited.

### codebook_tidy_data_set.rmd

This file is an automatically generated codebook for the tidy data set.  It was created using the package "dataMaid" and the function "makeCodebook()" 

### README_tidydataset.rmd

This file is the one you're currently reading.  It describes the basic descriptions of the file contained within the repo and the assignment objectives. 
